// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJgp1RUBs9VEpKXinA3xqjMe_Cb9PauYY',
    appId: '1:313087643941:web:188184e67f106830c50acc',
    messagingSenderId: '313087643941',
    projectId: 'mypersonalportfolio-f25e1',
    authDomain: 'mypersonalportfolio-f25e1.firebaseapp.com',
    storageBucket: 'mypersonalportfolio-f25e1.appspot.com',
    measurementId: 'G-9EQZYTBE06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5NTeyGYxDk-WkeVByE1ZsXDYFbp6TaZM',
    appId: '1:313087643941:android:289346d6226c153fc50acc',
    messagingSenderId: '313087643941',
    projectId: 'mypersonalportfolio-f25e1',
    storageBucket: 'mypersonalportfolio-f25e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa8i8VIbkfRjq-7oiRgBElL6C92kCWVdo',
    appId: '1:313087643941:ios:445845cbd48e3ecac50acc',
    messagingSenderId: '313087643941',
    projectId: 'mypersonalportfolio-f25e1',
    storageBucket: 'mypersonalportfolio-f25e1.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa8i8VIbkfRjq-7oiRgBElL6C92kCWVdo',
    appId: '1:313087643941:ios:d4581c15fe683b6ac50acc',
    messagingSenderId: '313087643941',
    projectId: 'mypersonalportfolio-f25e1',
    storageBucket: 'mypersonalportfolio-f25e1.appspot.com',
    iosBundleId: 'com.example.myPortfolio.RunnerTests',
  );
}
