// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArPVFMPUEKaX2Bc19JBoKUmvA4VZdeeTo',
    appId: '1:674743139704:web:785bbefbb19bdfbba41c8d',
    messagingSenderId: '674743139704',
    projectId: 'abhijeetsinghportfolio',
    authDomain: 'abhijeetsinghportfolio.firebaseapp.com',
    storageBucket: 'abhijeetsinghportfolio.appspot.com',
    measurementId: 'G-WDJ52DZQQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVT6OWtDTxrvrKmw7XuZn2jjJQUfo14V4',
    appId: '1:674743139704:android:077096fb522a124aa41c8d',
    messagingSenderId: '674743139704',
    projectId: 'abhijeetsinghportfolio',
    storageBucket: 'abhijeetsinghportfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_rmHcWTI-vdsOLmIiESIysq7sY301OqA',
    appId: '1:674743139704:ios:8cf9813743a1e8faa41c8d',
    messagingSenderId: '674743139704',
    projectId: 'abhijeetsinghportfolio',
    storageBucket: 'abhijeetsinghportfolio.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_rmHcWTI-vdsOLmIiESIysq7sY301OqA',
    appId: '1:674743139704:ios:8cf9813743a1e8faa41c8d',
    messagingSenderId: '674743139704',
    projectId: 'abhijeetsinghportfolio',
    storageBucket: 'abhijeetsinghportfolio.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArPVFMPUEKaX2Bc19JBoKUmvA4VZdeeTo',
    appId: '1:674743139704:web:ba2d87e3fc716cf6a41c8d',
    messagingSenderId: '674743139704',
    projectId: 'abhijeetsinghportfolio',
    authDomain: 'abhijeetsinghportfolio.firebaseapp.com',
    storageBucket: 'abhijeetsinghportfolio.appspot.com',
    measurementId: 'G-D146TYJV5P',
  );
}
